# 워크플로우의 이름
name: Postman API Test CI

# 어떤 이벤트가 발생했을 때 이 워크플로우를 실행할지 정의
on:
  push:
    branches: [ main ] # 'main' 브랜치에 push 이벤트가 발생했을 때만 실행

# 실행될 작업(Job)들을 정의
jobs:
  # 'newman-test' 라는 이름의 작업
  newman-test:
    # 이 작업이 실행될 가상 서버 환경을 지정 (우분투 최신 버전)
    runs-on: ubuntu-latest
    
    # 작업의 단계(Step)들을 정의
    steps:
      # 1. 코드를 가상 서버로 내려받는 단계
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. API 테스트에 필요한 Node.js 환경을 설치하는 단계
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Newman과 HTML 리포터를 설치하는 단계
      - name: Install Newman and HTML reporter
        run: npm install -g newman newman-reporter-html

      # 4. Newman 명령어를 실행하여 Postman 테스트를 수행하는 단계
      - name: Run API Tests
        run: newman run "MyTest.postman_collection.json" -r cli,html --reporter-html-export report.html
      
      # 5. 생성된 HTML 리포트 파일을 아티팩트(결과물)로 업로드하는 단계
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report # 결과물의 이름
          path: report.html   # 업로드할 파일